"""Typed schema contracts for the phase-1 Parquet artifacts.

One ordered {column: duckdb_type} dict per artifact, keyed by output filename.
Consumed by ``pipeline.utils.write_parquet_companion``: the Parquet companion of
each contract file is written by re-reading the just-written CSV all-VARCHAR and
CASTing every column to its contract type, so the Parquet is a typed rendering
of exactly what the CSV persisted (no dependence on in-memory dtypes).

Contract rules (phase-1: representational only — no value changes):
- ``cik``: VARCHAR. Values are cast verbatim; zero-padding NORMALIZATION is
  deliberately NOT applied here (a value change belongs in a later gated step).
- dates: DATE (pandas writes ISO yyyy-mm-dd).
- measures/rates: DOUBLE with true NULLs.
- integer-like ids/counts: BIGINT (cast through DOUBLE because pandas emits
  "1.0" for nullable int columns).
- 0/1 indicator columns written as ints today (``blocking_issue``,
  ``is_subsidiary``, ``row_key``) stay BIGINT — flipping to BOOLEAN would
  change the round-trip representation, which is out of scope for phase 1.
- known dirty mixed-content columns (``bdc_holdings.interest_rate``,
  ``face_amount``, ``realized/unrealized_gain_loss``) stay VARCHAR: they
  genuinely contain non-numeric text and are parsed downstream. Typing them
  DOUBLE would silently null real content. Revisit in phase 2.
- verbatim provenance metadata (``holdings_artifact_mtime``) stays VARCHAR.

Column order matters: it must exactly match what the writer emits. A mismatch
(missing, extra, or reordered columns) is schema drift and raises
``OutputSchemaError`` at write time rather than silently casting.

Plan: docs/production_stack/phase1_parquet_migration_plan.md
"""

ALLOWED_TYPES = {"VARCHAR", "DOUBLE", "BIGINT", "DATE", "BOOLEAN"}


class OutputSchemaError(RuntimeError):
    """Raised when a contract artifact's columns diverge from its schema."""


OUTPUT_SCHEMAS: dict[str, dict[str, str]] = {
    "source_reconciliation_detail.csv": {
        "status": "VARCHAR",
        "match_tier": "VARCHAR",
        "issue_severity": "VARCHAR",
        "residual_class": "VARCHAR",
        "blocking_issue": "BIGINT",
        "calibrated_status": "VARCHAR",
        "calibration_reason": "VARCHAR",
        "cik": "VARCHAR",
        "entity_name": "VARCHAR",
        "report_date": "DATE",
        "period": "DATE",
        "accession_number": "VARCHAR",
        "form_type": "VARCHAR",
        "filing_date": "DATE",
        "context_id": "VARCHAR",
        "source_row_id": "VARCHAR",
        "output_row_id": "VARCHAR",
        "raw_investment_identifier": "VARCHAR",
        "normalized_investment_identifier": "VARCHAR",
        "dimensions_raw": "VARCHAR",
        "concept_names": "VARCHAR",
        "source_wrapper_disposition": "VARCHAR",
        "source_wrapper_rule_id": "VARCHAR",
        "source_wrapper_family": "VARCHAR",
        "source_wrapper_parent_key": "VARCHAR",
        "source_wrapper_position_key": "VARCHAR",
        "source_wrapper_structured_leaf_key": "VARCHAR",
        "source_wrapper_investment_date_key": "VARCHAR",
        "source_wrapper_maturity_date_key": "VARCHAR",
        "source_wrapper_rate_key": "VARCHAR",
        "source_wrapper_signature_status": "VARCHAR",
        "source_wrapper_unparsed_remainder": "VARCHAR",
        "output_wrapper_disposition": "VARCHAR",
        "output_wrapper_rule_id": "VARCHAR",
        "output_wrapper_family": "VARCHAR",
        "output_wrapper_parent_key": "VARCHAR",
        "output_wrapper_position_key": "VARCHAR",
        "output_wrapper_structured_leaf_key": "VARCHAR",
        "output_wrapper_investment_date_key": "VARCHAR",
        "output_wrapper_maturity_date_key": "VARCHAR",
        "output_wrapper_rate_key": "VARCHAR",
        "output_wrapper_signature_status": "VARCHAR",
        "output_wrapper_unparsed_remainder": "VARCHAR",
        "source_fair_value": "DOUBLE",
        "output_fair_value": "DOUBLE",
        "source_cost": "DOUBLE",
        "output_cost": "DOUBLE",
        "source_principal_amount": "DOUBLE",
        "output_principal_amount": "DOUBLE",
        "source_shares_held": "DOUBLE",
        "output_shares_held": "DOUBLE",
        "source_interest_rate": "DOUBLE",
        "output_interest_rate": "DOUBLE",
        "source_basis_spread": "DOUBLE",
        "output_basis_spread": "DOUBLE",
        "source_pik_rate": "DOUBLE",
        "output_pik_rate": "DOUBLE",
        "mismatched_fields": "VARCHAR",
        "issuer_name": "VARCHAR",
        "instrument_description": "VARCHAR",
        "index_classification": "VARCHAR",
        "asset_category": "VARCHAR",
        "issuer_category": "VARCHAR",
        "non_private_market_disagreement": "VARCHAR",
        "aggregate_detection_disagreement": "VARCHAR",
        "hierarchy_parse_disagreement": "VARCHAR",
        "identifier_normalization_impact": "VARCHAR",
        "family_vs_asset_category_disagreement": "VARCHAR",
        "wrapper_leaf_staging_excluded": "VARCHAR",
        "evidence": "VARCHAR",
    },
    "private_markets_holdings.csv": {
        "source": "VARCHAR",
        "cik": "VARCHAR",
        "entity_name": "VARCHAR",
        "accession_number": "VARCHAR",
        "filing_date": "DATE",
        "report_date": "DATE",
        "issuer_name": "VARCHAR",
        "instrument_description": "VARCHAR",
        "cusip": "VARCHAR",
        "isin": "VARCHAR",
        "lei": "VARCHAR",
        "ticker": "VARCHAR",
        "fair_value": "DOUBLE",
        "cost": "DOUBLE",
        "pct_of_net_assets": "DOUBLE",
        "shares_held": "DOUBLE",
        "principal_amount": "DOUBLE",
        "fair_value_currency": "VARCHAR",
        "cost_currency": "VARCHAR",
        "principal_amount_currency": "VARCHAR",
        "principal_amount_usd": "DOUBLE",
        "principal_fx_rate_to_usd": "DOUBLE",
        "principal_fx_status": "VARCHAR",
        "asset_category": "VARCHAR",
        "issuer_category": "VARCHAR",
        "index_classification": "VARCHAR",
        "exposure_type": "VARCHAR",
        "asset_class": "VARCHAR",
        "fair_value_level": "VARCHAR",
        "interest_rate": "DOUBLE",
        "interest_rate_source": "VARCHAR",
        "basis_spread": "DOUBLE",
        "basis_spread_source": "VARCHAR",
        "reference_rate_type": "VARCHAR",
        "reference_rate_source": "VARCHAR",
        "coupon_type": "VARCHAR",
        "pik_rate": "DOUBLE",
        "maturity_date": "DATE",
        "maturity_date_source": "VARCHAR",
        "bdc_investment_identifier": "VARCHAR",
        "bdc_form_type": "VARCHAR",
        "bdc_dimensions_raw": "VARCHAR",
        "bdc_unrealized_gain_loss": "VARCHAR",
        "bdc_investment_country": "VARCHAR",
        "src_context_id": "VARCHAR",
        "src_context_count": "BIGINT",
        "src_conflict_fields": "VARCHAR",
        "src_transforms": "VARCHAR",
        "src_field_overrides": "VARCHAR",
        "cost_source": "VARCHAR",
        "shares_held_source": "VARCHAR",
        "fair_value_source": "VARCHAR",
        "principal_amount_source": "VARCHAR",
        "pct_of_net_assets_source": "VARCHAR",
        "pik_rate_source": "VARCHAR",
        "bdc_unrealized_gain_loss_source": "VARCHAR",
        "src_facts": "VARCHAR",
        "src_filled_fields": "VARCHAR",
        "corrected_fields": "VARCHAR",
        "nonaccrual_footnote": "BOOLEAN",
        "nonaccrual_dimension": "BOOLEAN",
        "nport_holding_id": "VARCHAR",
        "nport_series_name": "VARCHAR",
        "nport_series_id": "VARCHAR",
        "nport_asset_cat": "VARCHAR",
        "nport_issuer_type": "VARCHAR",
        "nport_payoff_profile": "VARCHAR",
        "nport_investment_country": "VARCHAR",
        "nport_is_restricted": "VARCHAR",
        "nport_quarter": "VARCHAR",
        "nport_is_default": "VARCHAR",
        "nport_are_interest_payments_in_arrears": "VARCHAR",
        "nport_is_paid_in_kind": "VARCHAR",
        "nport_currency_code": "VARCHAR",
        "nport_liquidity_classification": "VARCHAR",
        "is_subsidiary": "BIGINT",
        "axis_profile": "VARCHAR",
        "jv_subsidiary": "VARCHAR",
        "entity_id": "VARCHAR",
        "canonical_name": "VARCHAR",
        "extracted_industry": "VARCHAR",
        "gics_sub_industry": "VARCHAR",
        "lien_position": "VARCHAR",
        "instrument_type": "VARCHAR",
        "position_key": "VARCHAR",
        "position_id": "VARCHAR",
        "row_id": "VARCHAR",
        "row_id_basis": "VARCHAR",
    },
    "provenance_ledger.csv": {
        "row_id": "VARCHAR",
        "cik": "VARCHAR",
        "accession_number": "VARCHAR",
        "report_date": "DATE",
        "src_context_id": "VARCHAR",
        "src_facts": "VARCHAR",
        "field": "VARCHAR",
        "pathway": "VARCHAR",
        "declared_raw": "DOUBLE",
        "declared_events": "VARCHAR",
        "published": "DOUBLE",
        "expected": "DOUBLE",
        "cheap_status": "VARCHAR",
        "instance_raw": "DOUBLE",
        "full_status": "VARCHAR",
        "reason_code": "VARCHAR",
        "holdings_artifact_mtime": "VARCHAR",
    },
    "bdc_holdings.csv": {
        "period": "DATE",
        "investment_identifier": "VARCHAR",
        "industry": "VARCHAR",
        "investment_type": "VARCHAR",
        "affiliation": "VARCHAR",
        "dimensions_raw": "VARCHAR",
        "acquisition_date": "DATE",
        "basis_spread": "DOUBLE",
        "cost": "DOUBLE",
        "face_amount": "VARCHAR",
        "fair_value": "DOUBLE",
        "interest_rate": "VARCHAR",
        "interest_rate_floor": "DOUBLE",
        "maturity_date": "DATE",
        "pct_of_net_assets": "DOUBLE",
        "pik_rate": "DOUBLE",
        "principal_amount": "DOUBLE",
        "realized_gain_loss": "VARCHAR",
        "reference_rate_type": "VARCHAR",
        "shares_held": "DOUBLE",
        "unrealized_gain_loss": "VARCHAR",
        "fair_value_unit": "VARCHAR",
        "cost_unit": "VARCHAR",
        "principal_amount_unit": "VARCHAR",
        "interest_rate_concept": "VARCHAR",
        "src_facts": "VARCHAR",
        "nonaccrual_footnote": "BOOLEAN",
        "nonaccrual_dimension": "BOOLEAN",
        "cik": "VARCHAR",
        "entity_name": "VARCHAR",
        "accession_number": "VARCHAR",
        "form_type": "VARCHAR",
        "filing_date": "DATE",
        "report_date": "DATE",
        "dedupe_context_count": "BIGINT",
        "dedupe_conflict_fields": "VARCHAR",
        "dedupe_filled_fields": "VARCHAR",
        "dedupe_axis_split": "BOOLEAN",
        "src_context_id": "VARCHAR",
    },
    "bdc_ixbrl_field_status.csv": {
        "cik": "VARCHAR",
        "accession_number": "VARCHAR",
        "report_date": "DATE",
        "period": "DATE",
        "period_role": "VARCHAR",
        "anchor_class": "VARCHAR",
        "raw_id_lower": "VARCHAR",
        "maturity_date": "DATE",
        "maturity_status": "VARCHAR",
        "reference_rate_type": "VARCHAR",
        "reference_rate_status": "VARCHAR",
        "lien_position": "VARCHAR",
        "lien_status": "VARCHAR",
        "gics_sector": "VARCHAR",
        "sector_status": "VARCHAR",
        "lien_reconciled": "BOOLEAN",
        "in_unified": "BOOLEAN",
    },
    "row_validation_issues.csv": {
        "dataset": "VARCHAR",
        "source": "VARCHAR",
        "cik": "VARCHAR",
        "report_date": "DATE",
        # Mixed: integer positions AND 'ROW-<hash>' ids (full-data cast check
        # 2026-09-03).
        "row_key": "VARCHAR",
        "column": "VARCHAR",
        "rule_id": "VARCHAR",
        "severity": "VARCHAR",
        "evidence_strength": "VARCHAR",
        "status": "VARCHAR",
        "action": "VARCHAR",
        # Generic "offending value" across heterogeneous rules: mostly numeric
        # but carries strings (e.g. 'U_GBP' currency units). Full-data cast
        # check 2026-09-03 proved DOUBLE wrong here.
        "value": "VARCHAR",
        "message": "VARCHAR",
        "evidence": "VARCHAR",
        "row_id": "VARCHAR",
        "issuer_name": "VARCHAR",
        "bdc_investment_identifier": "VARCHAR",
    },
    "nport_holdings.csv": {
        "accession_number": "VARCHAR",
        "holding_id": "BIGINT",
        "issuer_name": "VARCHAR",
        "issuer_lei": "VARCHAR",
        "issuer_title": "VARCHAR",
        "issuer_cusip": "VARCHAR",
        "balance": "DOUBLE",
        "unit": "VARCHAR",
        "other_unit_desc": "VARCHAR",
        "currency_code": "VARCHAR",
        "currency_value": "DOUBLE",
        "exchange_rate": "DOUBLE",
        "percentage": "DOUBLE",
        "payoff_profile": "VARCHAR",
        "asset_cat": "VARCHAR",
        "other_asset": "VARCHAR",
        "issuer_type": "VARCHAR",
        "other_issuer": "VARCHAR",
        "investment_country": "VARCHAR",
        "is_restricted_security": "VARCHAR",
        "fair_value_level": "BIGINT",
        "derivative_cat": "VARCHAR",
        "maturity_date": "DATE",
        "coupon_type": "VARCHAR",
        "annualized_rate": "DOUBLE",
        "is_default": "VARCHAR",
        "are_any_interest_payment": "VARCHAR",
        "is_any_portion_interest_paid": "VARCHAR",
        "identifier_isin": "VARCHAR",
        "identifier_ticker": "VARCHAR",
        "other_identifier": "VARCHAR",
        "cik": "VARCHAR",
        "registrant_name": "VARCHAR",
        "filing_date": "DATE",
        "report_date": "DATE",
        "sub_type": "VARCHAR",
        "series_name": "VARCHAR",
        "series_id": "VARCHAR",
        "quarter": "VARCHAR",
        "sec_dataset_quarter": "VARCHAR",
    },
    "position_pik_status.csv": {
        "holding_row_id": "BIGINT",
        "source": "VARCHAR",
        "cik": "VARCHAR",
        "entity_name": "VARCHAR",
        "accession_number": "VARCHAR",
        "report_date": "DATE",
        "report_quarter": "VARCHAR",
        "issuer_name": "VARCHAR",
        "instrument_description": "VARCHAR",
        "position_id": "VARCHAR",
        "fair_value": "DOUBLE",
        "index_classification": "VARCHAR",
        "pik_current_status": "VARCHAR",
        "pik_current_flag": "BOOLEAN",
        "pik_current_evidence": "VARCHAR",
        "pik_current_amount": "DOUBLE",
        "pik_terms_flag": "BOOLEAN",
        "pik_terms_rate": "DOUBLE",
    },
    "position_matches.csv": {
        "cik": "VARCHAR",
        "entity_name": "VARCHAR",
        "source": "VARCHAR",
        "index_classification": "VARCHAR",
        "begin_quarter": "VARCHAR",
        "begin_report_date": "DATE",
        "begin_issuer_name": "VARCHAR",
        "begin_fair_value": "DOUBLE",
        "begin_cost": "DOUBLE",
        "begin_principal_amount": "DOUBLE",
        "begin_interest_rate": "DOUBLE",
        "begin_basis_spread": "DOUBLE",
        "begin_shares_held": "DOUBLE",
        "end_quarter": "VARCHAR",
        "end_report_date": "DATE",
        "end_issuer_name": "VARCHAR",
        "end_fair_value": "DOUBLE",
        "end_cost": "DOUBLE",
        "end_principal_amount": "DOUBLE",
        "end_interest_rate": "DOUBLE",
        "end_basis_spread": "DOUBLE",
        "end_shares_held": "DOUBLE",
        "match_method": "VARCHAR",
        "match_key": "VARCHAR",
        "match_score": "DOUBLE",
        "span_months": "BIGINT",
        "asset_category": "VARCHAR",
        "issuer_category": "VARCHAR",
        "maturity_date": "DATE",
        "coupon_type": "VARCHAR",
        "position_id": "VARCHAR",
    },
    "position_returns.csv": {
        "cik": "VARCHAR",
        "entity_name": "VARCHAR",
        "source": "VARCHAR",
        "begin_quarter": "VARCHAR",
        "end_quarter": "VARCHAR",
        "issuer_name": "VARCHAR",
        "index_classification": "VARCHAR",
        "asset_category": "VARCHAR",
        "begin_fair_value": "DOUBLE",
        "end_fair_value": "DOUBLE",
        "begin_cost": "DOUBLE",
        "end_cost": "DOUBLE",
        "begin_principal_amount": "DOUBLE",
        "end_principal_amount": "DOUBLE",
        "begin_shares_held": "DOUBLE",
        "end_shares_held": "DOUBLE",
        "begin_interest_rate": "DOUBLE",
        "begin_basis_spread": "DOUBLE",
        "income_rate": "DOUBLE",
        "pik_rate_pct": "DOUBLE",
        "fee_uplift_pct": "DOUBLE",
        "capital_return": "DOUBLE",
        "income_return": "DOUBLE",
        "total_return": "DOUBLE",
        "quarterly_total_return": "DOUBLE",
        "match_method": "VARCHAR",
        "match_score": "DOUBLE",
        "span_months": "BIGINT",
        "span_adjusted": "BOOLEAN",
        "position_id": "VARCHAR",
    },
    "position_id_edges.csv": {
        "edge_type": "VARCHAR",
        "position_id": "VARCHAR",
        "cik": "VARCHAR",
        "source": "VARCHAR",
        "begin_report_date": "DATE",
        "begin_quarter": "VARCHAR",
        "begin_issuer_name": "VARCHAR",
        "begin_fair_value": "DOUBLE",
        "end_report_date": "DATE",
        "end_quarter": "VARCHAR",
        "end_issuer_name": "VARCHAR",
        "end_fair_value": "DOUBLE",
        "match_method": "VARCHAR",
        "match_key": "VARCHAR",
        "match_score": "DOUBLE",
        "span_months": "BIGINT",
    },
}
